### ISSUE TITLE
remove VueJS I*sra*el - Facebook Page

### ISSUE THREAD

**Issue by HBO30** [vuejs/awesome-vue#4017]
who adds the criminal community here?

**Comment by Jogai** [comment]
Lets keep politics out of it.

**Comment by HBO30** [comment]
Lets keep politics out of it."

> 

can I ask you where are from .. anyway, when they steal your home and kick you out of your country  I would not say the same for you

**Comment by Jogai** [comment]
The point is we're not moderating on those kinds of things. There is a russian group as well, and most of the world is supporting Ukraine. But again, this list is not the place to moderate based on politics or countries policy (most likely the vue users in that country don't have anything to do with the policies of their country). Its a vue group, so it has a place on this list.

**Comment by Jogai** [comment]
Politics... Its a name that is standard according to ISO. This is not the platform to fight about that. I will not go into hypotheticals, but I will say that standards do play a big role in my decision making.

**Comment by HBO30** [comment]
Your decisions are contradictory. A few moments ago, you expressed your support for the Ukrainian cause, and then you say that the ISO plays a big role in your decision.
Do you outweigh the ISO on the humanitarian issue?
Give me answers, please

- Humanitarian issues do not play a role in your decisions?
- You don't believe me about my case?

**Comment by Jogai** [comment]
> you expressed your support for the Ukrainian cause

I didn't express my support. I just pointed to the fact that even if almost the whole world is in support of Ukraine we still have a Russian group on the list.

So I'm not contradicting myself.

What I'm doing is just moderating this repo a little bit, and I believe that I should do that in the interest of the list, and not based on opinions I have. You can see that because in this whole thread I'm trying to keep the conversation about the list (and the moderation of it), and not about outside factors. 

And btw ''play a big role" is not the same as "outweigh", because the former is not always 100% of the time, an the latter is taking precedence, which is not the same thing.

**Comment by HBO30** [comment]
> Lets keep politics out of it.

I just can't accept it... Maybe you don't believe what I'm saying, or you're far from the truth of what happened. In the end, politics will continue to play out issues like this.

I will tell about the fact of what happened
Israel is a state based on the occupation of Palestine by European Jews and all those who support them.
Anyone who raises the flag or the name of Israel or is affiliated with it supports the occupation in Palestine
Palestine is a state that has existed since eternity and will still
done.

"From the river to the sea, Palestine will be free"
#Palestinewillbefree
#palestine 🇵🇸

**Comment by moHaHa** [comment]
@Jogai 

 do you remember this "From the river to the sea, Palestine will be free"
 now Isreal planning to take Gaza from us also
 still this country listed as normal country?! ...  It is always and still  a country based on occupation of Palestine , and any one who take it's name that mean he support the occupation that hppend from 1948 to now  , and the Gaza Genocide that is in progress 


https://twitter.com/hashtag/GazaGenocide
