### ISSUE TITLE
Auto github stars bot?

### ISSUE THREAD

**Issue by angleman** [vuejs/awesome-vue#598]
Any update on when awesome-lists-bot for auto updating repo star counts will be in place? Ref: pull request [#452 Add script to update repository stars](https://github.com/vuejs/awesome-vue/pull/452)

Until the awesome-lists-bot is going people can view [README_STARS.md](https://github.com/angleman/awesome-vue/blob/master/README_STARS.md). Note sometimes the shields.io images don't load and you need to refresh your browser.

**Comment by devmattrick** [comment]
Might not be the most semantic solution, but instead of using a bot to push to the repository, maybe use images (similar to how CIs have the badge you can embed in Markdown) to update stars in semi-real time? The images can even be cached on whatever webserver is hosting it for a decent amount of time.

**Comment by qm3ster** [comment]
If anything, images would be more semantic as they would not pollute the edit history.
The use case calls precisely for badges.

**Comment by yieme** [comment]
It appears the README_STARS.md link above uses images.

**Comment by brillout** [comment]
Closing this for now as we don't display stars atm.
